#! /usr/bin/env python3

import sys, os

def Usage():
    print("""Usage: %s [-o outpath.vd] [-every Nframes] [-clampbefore frameno] infile.wf
Use black-hole path file as generated by 'bhinfo.py -trackpath/-invtrackpath file.wf',
write a corresponding .vd virdir path file.   Uses every N'th frame of the input path as a .vd key.
Defaults: -o <infile>.vd -every 10""" % sys.argv[0], file=sys.stderr)
    sys.exit(1)

ii = 1

outpath = None
every = 10
fps = 30
scale = 1.0
clampbeforeframe = None


while ii<len(sys.argv) and sys.argv[ii][0] == '-':
    opt = sys.argv[ii]; ii += 1
    if opt == '-o':
        outpath = sys.argv[ii]; ii += 1
    elif opt == '-every':
        every = int( sys.argv[ii] ); ii += 1
    elif opt == '-scale':
        scale = float( sys.argv[ii] ); ii += 1
    elif opt == '-clampbefore':
        clampbeforeframe = int( sys.argv[ii] ); ii += 1
    else:
        Usage()

if ii >= len(sys.argv):
    Usage()

inpath = sys.argv[ii]

if outpath is None:
    outpath = inpath.replace('.wf','') + '.vd'

clampbeforekey = None

frameno = 0
keys = []
keytimes = []
with open(inpath, 'r') as inwf:
    for line in inwf.readlines():
        ss = line.split('#')[0].split()
        if len(ss) >= 7:
            if frameno % every == 0:

                keytime = 0.0 + frameno / float(fps)
                keystr = " ".join(ss[0:6]) + "\t%g %s" % (scale, ss[6])
                keytimes.append(keytime)
                keys.append(keystr)

                if clampbeforeframe is not None and frameno >= clampbeforeframe and clampbeforekey is None:
                    for i in range( len(keys)-1 ):  # overwrite earlier keys if clampbefore'ing
                        keys[i] = keystr
                    clampbeforekey = len(keys)
            frameno += 1

with open(outpath, 'w') as outvd:
    print("fps %g" % fps, file=outvd)
    print("keys %d" % len(keys), file=outvd)
    for keytime, key in zip(keytimes, keys):
        print("%-9g :\t" % keytime, key, file=outvd)
